# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"5\n\x04voto\x12\x14\n\x0cid_candidato\x18\x01 \x01(\t\x12\x17\n\x0ftermo_candidato\x18\x02 \x01(\x05\"\xac\x01\n\x07\x65ntrada\x12\x10\n\x08id_lider\x18\x01 \x01(\t\x12\x13\n\x0btermo_lider\x18\x02 \x01(\x05\x12\x10\n\x08uncommit\x18\x03 \x01(\x08\x12\x13\n\x0buncommit_id\x18\x04 \x01(\x05\x12\x18\n\x10uncommit_command\x18\x05 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x06 \x01(\x08\x12\x11\n\tcommit_id\x18\x07 \x01(\x05\x12\x16\n\x0e\x63ommit_command\x18\x08 \x01(\t\"\"\n\x0f\x63omando_cliente\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\x1a\n\x07success\x12\x0f\n\x07success\x18\x01 \x01(\x08\"D\n\x10resposta_cliente\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\r\n\x05lider\x18\x03 \x01(\t\"%\n\x05lider\x12\r\n\x05lider\x18\x01 \x01(\t\x12\r\n\x05termo\x18\x02 \x01(\x05\x32\xa8\x01\n\tReplicate\x12\x1d\n\npedir_voto\x12\x05.voto\x1a\x08.success\x12%\n\x0f\x61nexar_entradas\x12\x08.entrada\x1a\x08.success\x12\x36\n\x0freceber_comando\x12\x10.comando_cliente\x1a\x11.resposta_cliente\x12\x1d\n\tset_lider\x12\x06.lider\x1a\x08.successb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTO']._serialized_start=14
  _globals['_VOTO']._serialized_end=67
  _globals['_ENTRADA']._serialized_start=70
  _globals['_ENTRADA']._serialized_end=242
  _globals['_COMANDO_CLIENTE']._serialized_start=244
  _globals['_COMANDO_CLIENTE']._serialized_end=278
  _globals['_SUCCESS']._serialized_start=280
  _globals['_SUCCESS']._serialized_end=306
  _globals['_RESPOSTA_CLIENTE']._serialized_start=308
  _globals['_RESPOSTA_CLIENTE']._serialized_end=376
  _globals['_LIDER']._serialized_start=378
  _globals['_LIDER']._serialized_end=415
  _globals['_REPLICATE']._serialized_start=418
  _globals['_REPLICATE']._serialized_end=586
# @@protoc_insertion_point(module_scope)
