# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import raft_pb2 as raft__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in raft_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicateStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.pedir_voto = channel.unary_unary(
                '/Replicate/pedir_voto',
                request_serializer=raft__pb2.voto.SerializeToString,
                response_deserializer=raft__pb2.success.FromString,
                _registered_method=True)
        self.anexar_entradas = channel.unary_unary(
                '/Replicate/anexar_entradas',
                request_serializer=raft__pb2.entrada.SerializeToString,
                response_deserializer=raft__pb2.success.FromString,
                _registered_method=True)
        self.receber_comando = channel.unary_unary(
                '/Replicate/receber_comando',
                request_serializer=raft__pb2.comando_cliente.SerializeToString,
                response_deserializer=raft__pb2.resposta_cliente.FromString,
                _registered_method=True)
        self.set_lider = channel.unary_unary(
                '/Replicate/set_lider',
                request_serializer=raft__pb2.lider.SerializeToString,
                response_deserializer=raft__pb2.success.FromString,
                _registered_method=True)


class ReplicateServicer:
    """Missing associated documentation comment in .proto file."""

    def pedir_voto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def anexar_entradas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def receber_comando(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set_lider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'pedir_voto': grpc.unary_unary_rpc_method_handler(
                    servicer.pedir_voto,
                    request_deserializer=raft__pb2.voto.FromString,
                    response_serializer=raft__pb2.success.SerializeToString,
            ),
            'anexar_entradas': grpc.unary_unary_rpc_method_handler(
                    servicer.anexar_entradas,
                    request_deserializer=raft__pb2.entrada.FromString,
                    response_serializer=raft__pb2.success.SerializeToString,
            ),
            'receber_comando': grpc.unary_unary_rpc_method_handler(
                    servicer.receber_comando,
                    request_deserializer=raft__pb2.comando_cliente.FromString,
                    response_serializer=raft__pb2.resposta_cliente.SerializeToString,
            ),
            'set_lider': grpc.unary_unary_rpc_method_handler(
                    servicer.set_lider,
                    request_deserializer=raft__pb2.lider.FromString,
                    response_serializer=raft__pb2.success.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Replicate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Replicate', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Replicate:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def pedir_voto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replicate/pedir_voto',
            raft__pb2.voto.SerializeToString,
            raft__pb2.success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def anexar_entradas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replicate/anexar_entradas',
            raft__pb2.entrada.SerializeToString,
            raft__pb2.success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def receber_comando(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replicate/receber_comando',
            raft__pb2.comando_cliente.SerializeToString,
            raft__pb2.resposta_cliente.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set_lider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replicate/set_lider',
            raft__pb2.lider.SerializeToString,
            raft__pb2.success.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
